[package]
name = "cqfrs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitintr = "0.3.0"
libc = "0.2.147"
parking_lot = "0.12.1"
rand = "0.8.5"


[features]
debug = []

# bitintr is abandoned
[patch.crates-io]
bitintr = { git = "https://github.com/finnbear/bitintr", branch = "remove_nightly" }